# Chruby
source $BREW_HOME/opt/chruby/share/chruby/chruby.sh
chruby 2.1.0

# Node Version Manager (nvm)
source $BREW_HOME/opt/nvm/nvm.sh
export NVM_DIR=~/.nvm
nvm use 0.11.13 > /dev/null 2>&1

# Oracle stuff
export ORACLE_IC_HOME="$HOME/.oracle/instantclient_11_2"
export DYLD_LIBRARY_PATH=$ORACLE_IC_HOME:$DYLD_LIBRARY_PATH
