#
# Exports
#

# Homebrew path + smoketest
export PATH=/usr/local/bin:$PATH
export BREW_HOME=$(brew --prefix)

# Oracle Instant Client reqs
export ORACLE_IC_HOME="$HOME/.oracle/instantclient_11_2"
export DYLD_LIBRARY_PATH=$ORACLE_IC_HOME:$DYLD_LIBRARY_PATH

# oh-my-zsh pre-heat
export ZSH=$HOME/.oh-my-zsh

# Force UTF-8 en-US language environment
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

# Default editor
export EDITOR='nvim'

# Custom/old Firefox for Selenium tests
export SELENIUM_FIREFOX='/Applications/Firefox 3.6.28.app/Contents/MacOS/firefox-bin'

# Fzf
# Don't display hidden/dot-prefixed matches
export FZF_DEFAULT_COMMAND='
  (find * -name ".*" -prune -o -type f -print -o -type l -print) 2> /dev/null'
