#
# Local ENV vars
#

# Custom theme
ZSH_THEME="aledovsky"
DEFAULT_USER=$USER

# Disable automatic terminal naming
DISABLE_AUTO_TITLE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# oh-my-zsh plugins
plugins=(git extract bundler)

#
# Aliases
#

alias v='nocorrect vim'
alias a='nocorrect ag'
alias ssh='TERM=xterm ssh'
alias gh='gem_home'

#
# Sourcings
#

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Z - fast directory traversal
source $BREW_HOME/etc/profile.d/z.sh

# gem_home (superseeded chgems)
source $BREW_HOME/share/gem_home/gem_home.sh

# Base16 shell colors setup
source "$HOME/.config/base16-shell/base16-twilight.dark.sh"

#
# Misc
#

# Make <C-s> work in CommandT
# https://github.com/wincent/Command-T/blob/master/doc/command-t.txt
stty -ixon

# Fixes issue with gem_home (https://github.com/postmodern/gem_home/issues/7)
unsetopt auto_pushd
unsetopt pushd_ignore_dups
