#
# Exports
#

# Homebrew path + smoketest
export PATH=/usr/local/bin:$PATH
export BREW_HOME=$(brew --prefix)

# Oracle Instant Client reqs
export ORACLE_IC_HOME="$HOME/.oracle/instantclient_11_2"
export DYLD_LIBRARY_PATH=$ORACLE_IC_HOME:$DYLD_LIBRARY_PATH

# oh-my-zsh pre-heat
export ZSH=$HOME/.oh-my-zsh

# Force UTF-8 en-US language environment
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

# Default editor
export EDITOR='vim'

# Custom/old Firefox for Selenium tests
export SELENIUM_FIREFOX='/Applications/Firefox 3.6.28.app/Contents/MacOS/firefox-bin'

#
# Local ENV vars
#

# Custom theme
ZSH_THEME="aledovsky"
DEFAULT_USER=$USER

# Disable automatic terminal naming
DISABLE_AUTO_TITLE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# oh-my-zsh plugins
plugins=(git extract bundle)

#
# Aliases
#

alias v='nocorrect vim'
alias a='nocorrect ag'
alias ssh='TERM=xterm ssh'
alias gh='gem_home'

#
# Sourcings
#

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Z - fast directory traversal
source $BREW_HOME/etc/profile.d/z.sh

# gem_home (superseeded chgems)
source $BREW_HOME/share/gem_home/gem_home.sh

#
# Misc
#

# Make <C-s> work in CommandT
# https://github.com/wincent/Command-T/blob/master/doc/command-t.txt
stty -ixon
